name: Branch Protection
description: set protection rule to main branch

inputs:
  GH_TOKEN:
    required: true
    description: access token
  REPO:
    required: true
    description: repo path

runs:
  using: "composite"
  steps:
    - name: Branch Protection
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
        REPO: ${{ inputs.REPO }}
      shell: bash
      run: |
        gh api -X PATCH /repos/$REPO -f allow_auto_merge=true
        echo '{
          "required_linear_history": true,
          "enforce_admins": true,
          "required_pull_request_reviews": null,
          "restrictions": null,
          "required_status_checks": {
            "strict": true,
            "contexts": ["Build-and-Test"]
          }
        }' | gh api -X PUT /repos/$REPO/branches/main/protection \
          -H "Accept: application/vnd.github.v3+json" \
          --input -
