name: Build

inputs:
  FOLDER_PATH:
    required: true

runs:
  using: "composite"
  steps:
    - name: test
      env:
        FOLDER_PATH: ${{ inputs.FOLDER_PATH}}
      shell: bash
      run: |
        npm test
