name: E2E Tests
description: E2E tests to npm typescript package

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Set-Up local npm registry
      shell: bash
      run: |
        cat <<EOF > verdaccio-config.yaml
        storage: ./verdaccio-storage
        auth:
          htpasswd:
            file: ./htpasswd
        packages:
          '**':
            access: \$all
            publish: \$all
        EOF
        npx verdaccio --config verdaccio-config.yaml --listen 4873 &
        npx wait-on http://localhost:4873

    - name: publish to local npm registry
      shell: bash
      run: |
        npm config set registry http://localhost:4873
        npm config set //localhost:4873/:_authToken "dummy-token"
        npm publish

    - name: Run E2E Package Test
      shell: bash
      run: |
        export PACK_NAME=$(jq -r '.name' package.json)
        mkdir -p test
        cd test
        npm init -y
        npm pkg set type="module"
        npm install $PACK_NAME --registry http://localhost:4873
        bash test_init
        node test.js
