name: Build and Test

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "npm"

    - name: Build and Test
      shell: bash
      run: |
        npm ci
        npm run build
        npm run lint
        npm run test
