name: Build and Test
description: "Install and test my npm package"

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "npm"

    - name: Build and Test
      shell: bash
      run: |
        npm ci
        npm build
        npm int
        npm test
